/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { CreateTenantRequestMode } from './createTenantRequestMode';
import type { CreateTenantRequestPlan } from './createTenantRequestPlan';
import type { CreateTenantRequestMetadata } from './createTenantRequestMetadata';

export interface CreateTenantRequest {
  /**
   * Tenant company name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Tenant contact email */
  email: string;
  /** Integration mode */
  mode: CreateTenantRequestMode;
  /** Paid.ai API key (required for BYOK mode) */
  paidApiKey?: string;
  /** Subscription plan tier */
  plan?: CreateTenantRequestPlan;
  /** Additional tenant metadata */
  metadata?: CreateTenantRequestMetadata;
}
