/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { CreateExperimentRequestVariantsItem } from './createExperimentRequestVariantsItem';

export interface CreateExperimentRequest {
  /**
   * Experiment key (lowercase, numbers, underscores only)
   * @pattern ^[a-z0-9_]+$
   */
  key: string;
  /**
   * Experiment name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Experiment description
   * @maxLength 1000
   */
  description?: string;
  /**
   * @minItems 2
   * @maxItems 10
   */
  variants: CreateExperimentRequestVariantsItem[];
  /**
   * Target number of samples
   * @minimum 1
   */
  targetSampleSize?: number;
}
