/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { ExperimentDefinitionStatus } from './experimentDefinitionStatus';
import type { ExperimentDefinitionVariantsItem } from './experimentDefinitionVariantsItem';
import type { ExperimentDefinitionMetadata } from './experimentDefinitionMetadata';

export interface ExperimentDefinition {
  /** Experiment key identifier */
  experimentId?: string;
  /** Experiment UUID */
  id?: string;
  /** Human-readable experiment name */
  name?: string;
  /** Experiment description */
  description?: string;
  /** Current experiment status */
  status?: ExperimentDefinitionStatus;
  /** List of experiment variants with prices */
  variants?: ExperimentDefinitionVariantsItem[];
  /** Target sample size for the experiment */
  targetSampleSize?: number;
  /** Experiment start date */
  startDate?: string;
  /** Experiment end date */
  endDate?: string;
  /** Additional experiment metadata */
  metadata?: ExperimentDefinitionMetadata;
}
