/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { GetApiTenantsMode } from './getApiTenantsMode';
import type { GetApiTenantsPlan } from './getApiTenantsPlan';

export type GetApiTenantsParams = {
/**
 * Filter by mode
 */
mode?: GetApiTenantsMode;
/**
 * Filter by plan tier
 */
plan?: GetApiTenantsPlan;
/**
 * Number of results to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Offset for pagination
 * @minimum 0
 */
offset?: number;
};
