/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */

/**
 * Optimization objective (revenue, conversion, or profit)
 */
export type JaleOptimizeRequestObjective = typeof JaleOptimizeRequestObjective[keyof typeof JaleOptimizeRequestObjective];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JaleOptimizeRequestObjective = {
  revenue: 'revenue',
  conversion: 'conversion',
  profit: 'profit',
} as const;
