/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { JaleOptimizeRequestObjective } from './jaleOptimizeRequestObjective';

export interface JaleOptimizeRequest {
  /** Unique identifier for the experiment to optimize */
  experimentId: string;
  /** Optimization objective (revenue, conversion, or profit) */
  objective?: JaleOptimizeRequestObjective;
  /** Optional list of candidate prices to evaluate */
  candidates?: number[];
  /**
   * Number of days of historical data to consider
   * @minimum 1
   */
  lookbackDays?: number;
}
