/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { PriceSimulation } from './priceSimulation';

export interface JaleOptimizeResponse {
  /** The recommended optimal price */
  recommendedPrice?: number;
  /** Expected revenue at the recommended price */
  expectedRevenue?: number;
  /**
   * Confidence score for the recommendation (0-1)
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
  /** Revenue simulation results for all candidate prices */
  simulation?: PriceSimulation[];
}
