/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { ProposeVariantResponseVariant } from './proposeVariantResponseVariant';
import type { ProposeVariantResponseExperiment } from './proposeVariantResponseExperiment';

export interface ProposeVariantResponse {
  /** Whether the variant was successfully proposed */
  success?: boolean;
  /** Experiment key identifier */
  experimentId?: string;
  /** The newly proposed variant */
  variant?: ProposeVariantResponseVariant;
  /** Success message */
  message?: string;
  /** Updated experiment details */
  experiment?: ProposeVariantResponseExperiment;
}
