/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { ProposeVariantRequestMetadata } from './proposeVariantRequestMetadata';

export interface ProposeVariantRequest {
  /** Unique identifier for the experiment (UUID or key) */
  experimentId: string;
  /** Tenant ID for multi-tenant key lookup */
  tenantId?: string;
  /**
   * Price for the new variant
   * @minimum 0
   * @exclusiveMinimum
   */
  price: number;
  /** Optional label for the variant (auto-generated if not provided) */
  label?: string;
  /** Additional metadata for the variant */
  metadata?: ProposeVariantRequestMetadata;
}
