/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type { TenantMode } from './tenantMode';
import type { TenantPlan } from './tenantPlan';
import type { TenantMetadata } from './tenantMetadata';

export interface Tenant {
  /** Unique tenant identifier */
  id: string;
  /** Tenant company name */
  name: string;
  /** Tenant contact email */
  email: string;
  /** Integration mode (managed uses platform key, byok uses tenant's key) */
  mode: TenantMode;
  /** Masked Paid.ai API key (only shown for BYOK mode) */
  paidApiKey?: string;
  /** Subscription plan tier */
  plan: TenantPlan;
  /** Secret for webhook signature verification (masked) */
  webhookSecret?: string;
  /** Tenant creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Additional tenant metadata */
  metadata?: TenantMetadata;
}
