/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type {
  Error,
  GetApiDebugAssignments200
} from '.././schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Returns all current experiment assignments for debugging purposes.
Only available in development mode.

 * @summary Get all experiment assignments
 */
export type getApiDebugAssignmentsResponse200 = {
  data: GetApiDebugAssignments200
  status: 200
}

export type getApiDebugAssignmentsResponse403 = {
  data: Error
  status: 403
}
    
export type getApiDebugAssignmentsResponseSuccess = (getApiDebugAssignmentsResponse200) & {
  headers: Headers;
};
export type getApiDebugAssignmentsResponseError = (getApiDebugAssignmentsResponse403) & {
  headers: Headers;
};

export type getApiDebugAssignmentsResponse = (getApiDebugAssignmentsResponseSuccess | getApiDebugAssignmentsResponseError)

export const getGetApiDebugAssignmentsUrl = () => {


  

  return `/api/api/debug/assignments`
}

export const getApiDebugAssignments = async ( options?: RequestInit): Promise<getApiDebugAssignmentsResponse> => {
  
  return customFetch<getApiDebugAssignmentsResponse>(getGetApiDebugAssignmentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


