/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type {
  Error,
  WebhookEvent
} from '.././schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Receives webhook events from Paid.ai about subscriptions, payments, and other billing events.
Links these events to A/B test experiments for conversion tracking.

**Security**: In production, webhook signatures should be verified using the WEBHOOK_SECRET.

 * @summary Paid.ai webhook endpoint
 */
export type postWebhooksPaidResponse200 = {
  data: string
  status: 200
}

export type postWebhooksPaidResponse400 = {
  data: Error
  status: 400
}

export type postWebhooksPaidResponse401 = {
  data: Error
  status: 401
}

export type postWebhooksPaidResponse500 = {
  data: Error
  status: 500
}
    
export type postWebhooksPaidResponseSuccess = (postWebhooksPaidResponse200) & {
  headers: Headers;
};
export type postWebhooksPaidResponseError = (postWebhooksPaidResponse400 | postWebhooksPaidResponse401 | postWebhooksPaidResponse500) & {
  headers: Headers;
};

export type postWebhooksPaidResponse = (postWebhooksPaidResponseSuccess | postWebhooksPaidResponseError)

export const getPostWebhooksPaidUrl = () => {


  

  return `/api/webhooks/paid`
}

export const postWebhooksPaid = async (webhookEvent: WebhookEvent, options?: RequestInit): Promise<postWebhooksPaidResponse> => {
  
  return customFetch<postWebhooksPaidResponse>(getPostWebhooksPaidUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      webhookEvent,)
  }
);}


