/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type {
  Error,
  JaleOptimizeRequest,
  JaleOptimizeResponse,
  ProposeVariantRequest,
  ProposeVariantResponse
} from '.././schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Calls the jale service to recommend an optimal price based on experiment data.
Uses historical conversion and revenue data to simulate expected outcomes for candidate prices.

The endpoint analyzes experiment results and returns a recommended price along with
confidence score and revenue simulation data.

 * @summary Get pricing recommendation from jale optimization
 */
export type postApiJaleOptimizeResponse200 = {
  data: JaleOptimizeResponse
  status: 200
}

export type postApiJaleOptimizeResponse400 = {
  data: Error
  status: 400
}

export type postApiJaleOptimizeResponse500 = {
  data: Error
  status: 500
}
    
export type postApiJaleOptimizeResponseSuccess = (postApiJaleOptimizeResponse200) & {
  headers: Headers;
};
export type postApiJaleOptimizeResponseError = (postApiJaleOptimizeResponse400 | postApiJaleOptimizeResponse500) & {
  headers: Headers;
};

export type postApiJaleOptimizeResponse = (postApiJaleOptimizeResponseSuccess | postApiJaleOptimizeResponseError)

export const getPostApiJaleOptimizeUrl = () => {


  

  return `/api/api/jale/optimize`
}

export const postApiJaleOptimize = async (jaleOptimizeRequest: JaleOptimizeRequest, options?: RequestInit): Promise<postApiJaleOptimizeResponse> => {
  
  return customFetch<postApiJaleOptimizeResponse>(getPostApiJaleOptimizeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      jaleOptimizeRequest,)
  }
);}


/**
 * Allows jale to propose a new pricing variant to be added to an existing experiment.
This can be used after jale's optimization to create a new test variant based on
recommendations. The new variant starts with zero weight until explicitly activated.

 * @summary Propose a new variant for an experiment
 */
export type postApiJaleProposeVariantResponse200 = {
  data: ProposeVariantResponse
  status: 200
}

export type postApiJaleProposeVariantResponse400 = {
  data: Error
  status: 400
}

export type postApiJaleProposeVariantResponse404 = {
  data: Error
  status: 404
}

export type postApiJaleProposeVariantResponse500 = {
  data: Error
  status: 500
}
    
export type postApiJaleProposeVariantResponseSuccess = (postApiJaleProposeVariantResponse200) & {
  headers: Headers;
};
export type postApiJaleProposeVariantResponseError = (postApiJaleProposeVariantResponse400 | postApiJaleProposeVariantResponse404 | postApiJaleProposeVariantResponse500) & {
  headers: Headers;
};

export type postApiJaleProposeVariantResponse = (postApiJaleProposeVariantResponseSuccess | postApiJaleProposeVariantResponseError)

export const getPostApiJaleProposeVariantUrl = () => {


  

  return `/api/api/jale/propose-variant`
}

export const postApiJaleProposeVariant = async (proposeVariantRequest: ProposeVariantRequest, options?: RequestInit): Promise<postApiJaleProposeVariantResponse> => {
  
  return customFetch<postApiJaleProposeVariantResponse>(getPostApiJaleProposeVariantUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      proposeVariantRequest,)
  }
);}


