/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * A/B Testing Server for Pricing Experiments
 * Server for conducting A/B testing experiments on pricing strategies using Paid.ai integration.

This server provides endpoints for:
- Assigning users to experiment variants
- Tracking pricing page views and conversions
- Processing Paid.ai webhook events
- Analyzing experiment results

**Architecture**: The system uses deterministic SHA-256 hashing to ensure consistent user-to-variant mapping,
emits signals to Paid.ai's Signals API for event tracking, and provides real-time analytics.

 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateExperimentRequest,
  CreateTenantRequest,
  Error,
  Experiment,
  GetApiTenants200,
  GetApiTenantsParams,
  GetApiTenantsTenantIdExperiments200,
  GetApiTenantsTenantIdExperimentsParams,
  Tenant,
  UpdateTenantRequest
} from '.././schemas';

import { customFetch } from '.././custom-fetch';

/**
 * Create a new tenant account with either Managed or BYOK (Bring Your Own Key) mode.
In Managed mode, the platform handles Paid.ai integration. In BYOK mode, the tenant
provides their own Paid.ai API key.

 * @summary Create a new tenant
 */
export type postApiTenantsResponse201 = {
  data: Tenant
  status: 201
}

export type postApiTenantsResponse400 = {
  data: Error
  status: 400
}

export type postApiTenantsResponse409 = {
  data: Error
  status: 409
}

export type postApiTenantsResponse500 = {
  data: Error
  status: 500
}
    
export type postApiTenantsResponseSuccess = (postApiTenantsResponse201) & {
  headers: Headers;
};
export type postApiTenantsResponseError = (postApiTenantsResponse400 | postApiTenantsResponse409 | postApiTenantsResponse500) & {
  headers: Headers;
};

export type postApiTenantsResponse = (postApiTenantsResponseSuccess | postApiTenantsResponseError)

export const getPostApiTenantsUrl = () => {


  

  return `/api/api/tenants`
}

export const postApiTenants = async (createTenantRequest: CreateTenantRequest, options?: RequestInit): Promise<postApiTenantsResponse> => {
  
  return customFetch<postApiTenantsResponse>(getPostApiTenantsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTenantRequest,)
  }
);}


/**
 * Get a list of all tenants (admin only)
 * @summary List tenants
 */
export type getApiTenantsResponse200 = {
  data: GetApiTenants200
  status: 200
}

export type getApiTenantsResponse401 = {
  data: Error
  status: 401
}

export type getApiTenantsResponse500 = {
  data: Error
  status: 500
}
    
export type getApiTenantsResponseSuccess = (getApiTenantsResponse200) & {
  headers: Headers;
};
export type getApiTenantsResponseError = (getApiTenantsResponse401 | getApiTenantsResponse500) & {
  headers: Headers;
};

export type getApiTenantsResponse = (getApiTenantsResponseSuccess | getApiTenantsResponseError)

export const getGetApiTenantsUrl = (params?: GetApiTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/tenants?${stringifiedParams}` : `/api/api/tenants`
}

export const getApiTenants = async (params?: GetApiTenantsParams, options?: RequestInit): Promise<getApiTenantsResponse> => {
  
  return customFetch<getApiTenantsResponse>(getGetApiTenantsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Retrieve information about a specific tenant
 * @summary Get tenant details
 */
export type getApiTenantsTenantIdResponse200 = {
  data: Tenant
  status: 200
}

export type getApiTenantsTenantIdResponse404 = {
  data: Error
  status: 404
}

export type getApiTenantsTenantIdResponse500 = {
  data: Error
  status: 500
}
    
export type getApiTenantsTenantIdResponseSuccess = (getApiTenantsTenantIdResponse200) & {
  headers: Headers;
};
export type getApiTenantsTenantIdResponseError = (getApiTenantsTenantIdResponse404 | getApiTenantsTenantIdResponse500) & {
  headers: Headers;
};

export type getApiTenantsTenantIdResponse = (getApiTenantsTenantIdResponseSuccess | getApiTenantsTenantIdResponseError)

export const getGetApiTenantsTenantIdUrl = (tenantId: string,) => {


  

  return `/api/api/tenants/${tenantId}`
}

export const getApiTenantsTenantId = async (tenantId: string, options?: RequestInit): Promise<getApiTenantsTenantIdResponse> => {
  
  return customFetch<getApiTenantsTenantIdResponse>(getGetApiTenantsTenantIdUrl(tenantId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * Update tenant settings (mode, API key, plan, etc.)
 * @summary Update tenant
 */
export type patchApiTenantsTenantIdResponse200 = {
  data: Tenant
  status: 200
}

export type patchApiTenantsTenantIdResponse400 = {
  data: Error
  status: 400
}

export type patchApiTenantsTenantIdResponse404 = {
  data: Error
  status: 404
}

export type patchApiTenantsTenantIdResponse500 = {
  data: Error
  status: 500
}
    
export type patchApiTenantsTenantIdResponseSuccess = (patchApiTenantsTenantIdResponse200) & {
  headers: Headers;
};
export type patchApiTenantsTenantIdResponseError = (patchApiTenantsTenantIdResponse400 | patchApiTenantsTenantIdResponse404 | patchApiTenantsTenantIdResponse500) & {
  headers: Headers;
};

export type patchApiTenantsTenantIdResponse = (patchApiTenantsTenantIdResponseSuccess | patchApiTenantsTenantIdResponseError)

export const getPatchApiTenantsTenantIdUrl = (tenantId: string,) => {


  

  return `/api/api/tenants/${tenantId}`
}

export const patchApiTenantsTenantId = async (tenantId: string,
    updateTenantRequest: UpdateTenantRequest, options?: RequestInit): Promise<patchApiTenantsTenantIdResponse> => {
  
  return customFetch<patchApiTenantsTenantIdResponse>(getPatchApiTenantsTenantIdUrl(tenantId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTenantRequest,)
  }
);}


/**
 * Delete a tenant and all associated data
 * @summary Delete tenant
 */
export type deleteApiTenantsTenantIdResponse204 = {
  data: void
  status: 204
}

export type deleteApiTenantsTenantIdResponse404 = {
  data: Error
  status: 404
}

export type deleteApiTenantsTenantIdResponse500 = {
  data: Error
  status: 500
}
    
export type deleteApiTenantsTenantIdResponseSuccess = (deleteApiTenantsTenantIdResponse204) & {
  headers: Headers;
};
export type deleteApiTenantsTenantIdResponseError = (deleteApiTenantsTenantIdResponse404 | deleteApiTenantsTenantIdResponse500) & {
  headers: Headers;
};

export type deleteApiTenantsTenantIdResponse = (deleteApiTenantsTenantIdResponseSuccess | deleteApiTenantsTenantIdResponseError)

export const getDeleteApiTenantsTenantIdUrl = (tenantId: string,) => {


  

  return `/api/api/tenants/${tenantId}`
}

export const deleteApiTenantsTenantId = async (tenantId: string, options?: RequestInit): Promise<deleteApiTenantsTenantIdResponse> => {
  
  return customFetch<deleteApiTenantsTenantIdResponse>(getDeleteApiTenantsTenantIdUrl(tenantId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * Create a new A/B testing experiment for a specific tenant
 * @summary Create experiment for tenant
 */
export type postApiTenantsTenantIdExperimentsResponse201 = {
  data: Experiment
  status: 201
}

export type postApiTenantsTenantIdExperimentsResponse400 = {
  data: Error
  status: 400
}

export type postApiTenantsTenantIdExperimentsResponse404 = {
  data: Error
  status: 404
}

export type postApiTenantsTenantIdExperimentsResponse500 = {
  data: Error
  status: 500
}
    
export type postApiTenantsTenantIdExperimentsResponseSuccess = (postApiTenantsTenantIdExperimentsResponse201) & {
  headers: Headers;
};
export type postApiTenantsTenantIdExperimentsResponseError = (postApiTenantsTenantIdExperimentsResponse400 | postApiTenantsTenantIdExperimentsResponse404 | postApiTenantsTenantIdExperimentsResponse500) & {
  headers: Headers;
};

export type postApiTenantsTenantIdExperimentsResponse = (postApiTenantsTenantIdExperimentsResponseSuccess | postApiTenantsTenantIdExperimentsResponseError)

export const getPostApiTenantsTenantIdExperimentsUrl = (tenantId: string,) => {


  

  return `/api/api/tenants/${tenantId}/experiments`
}

export const postApiTenantsTenantIdExperiments = async (tenantId: string,
    createExperimentRequest: CreateExperimentRequest, options?: RequestInit): Promise<postApiTenantsTenantIdExperimentsResponse> => {
  
  return customFetch<postApiTenantsTenantIdExperimentsResponse>(getPostApiTenantsTenantIdExperimentsUrl(tenantId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createExperimentRequest,)
  }
);}


/**
 * Get all experiments for a specific tenant
 * @summary List tenant experiments
 */
export type getApiTenantsTenantIdExperimentsResponse200 = {
  data: GetApiTenantsTenantIdExperiments200
  status: 200
}

export type getApiTenantsTenantIdExperimentsResponse404 = {
  data: Error
  status: 404
}

export type getApiTenantsTenantIdExperimentsResponse500 = {
  data: Error
  status: 500
}
    
export type getApiTenantsTenantIdExperimentsResponseSuccess = (getApiTenantsTenantIdExperimentsResponse200) & {
  headers: Headers;
};
export type getApiTenantsTenantIdExperimentsResponseError = (getApiTenantsTenantIdExperimentsResponse404 | getApiTenantsTenantIdExperimentsResponse500) & {
  headers: Headers;
};

export type getApiTenantsTenantIdExperimentsResponse = (getApiTenantsTenantIdExperimentsResponseSuccess | getApiTenantsTenantIdExperimentsResponseError)

export const getGetApiTenantsTenantIdExperimentsUrl = (tenantId: string,
    params?: GetApiTenantsTenantIdExperimentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/tenants/${tenantId}/experiments?${stringifiedParams}` : `/api/api/tenants/${tenantId}/experiments`
}

export const getApiTenantsTenantIdExperiments = async (tenantId: string,
    params?: GetApiTenantsTenantIdExperimentsParams, options?: RequestInit): Promise<getApiTenantsTenantIdExperimentsResponse> => {
  
  return customFetch<getApiTenantsTenantIdExperimentsResponse>(getGetApiTenantsTenantIdExperimentsUrl(tenantId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


