import { AgentAccount, Transaction, DashboardStats } from './types';

// Sample Accounts
export const sampleAccounts: AgentAccount[] = [
  {
    id: 'acc_001',
    agentId: 'agent_gpt4',
    agentName: 'GPT-4 Research Agent',
    balance: 1250.50,
    currency: 'USD',
    status: 'active',
    accountType: 'premium',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-05'),
    monthlyLimit: 5000,
    usageThisMonth: 1250.50,
  },
  {
    id: 'acc_002',
    agentId: 'agent_claude',
    agentName: 'Claude Trading Bot',
    balance: 89.25,
    currency: 'USD',
    status: 'payment_required',
    accountType: 'standard',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-12-05'),
    monthlyLimit: 1000,
    usageThisMonth: 910.75,
  },
  {
    id: 'acc_003',
    agentId: 'agent_data_pipeline',
    agentName: 'Data Pipeline Agent',
    balance: 5420.00,
    currency: 'USD',
    status: 'active',
    accountType: 'enterprise',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-12-05'),
    usageThisMonth: 2100.00,
  },
  {
    id: 'acc_004',
    agentId: 'agent_crypto_monitor',
    agentName: 'Crypto Monitor Agent',
    balance: 450.75,
    currency: 'USD',
    status: 'active',
    accountType: 'standard',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-12-05'),
    monthlyLimit: 1000,
    usageThisMonth: 549.25,
  },
];

// Sample Transactions
export const sampleTransactions: Transaction[] = [
  {
    id: 'txn_001',
    accountId: 'acc_001',
    type: 'debit',
    amount: 25.50,
    currency: 'USD',
    status: 'completed',
    description: 'API call - Data processing',
    category: 'api_usage',
    metadata: {
      apiEndpoint: '/api/v1/process',
      requestId: 'req_xyz123',
      agentAction: 'data_analysis',
    },
    createdAt: new Date('2024-12-05T10:30:00'),
    completedAt: new Date('2024-12-05T10:30:02'),
  },
  {
    id: 'txn_002',
    accountId: 'acc_002',
    type: 'debit',
    amount: 150.00,
    currency: 'USD',
    status: 'payment_required',
    description: 'Premium API access attempt',
    category: 'api_usage',
    metadata: {
      apiEndpoint: '/api/v1/trade',
      requestId: 'req_abc456',
      agentAction: 'execute_trade',
    },
    createdAt: new Date('2024-12-05T11:15:00'),
  },
  {
    id: 'txn_003',
    accountId: 'acc_001',
    type: 'credit',
    amount: 500.00,
    currency: 'USD',
    status: 'completed',
    description: 'Account top-up',
    category: 'deposit',
    createdAt: new Date('2024-12-04T14:20:00'),
    completedAt: new Date('2024-12-04T14:20:05'),
  },
  {
    id: 'txn_004',
    accountId: 'acc_003',
    type: 'debit',
    amount: 75.00,
    currency: 'USD',
    status: 'completed',
    description: 'Bulk data transfer',
    category: 'data_transfer',
    metadata: {
      apiEndpoint: '/api/v1/bulk-transfer',
      requestId: 'req_def789',
      agentAction: 'bulk_data_sync',
    },
    createdAt: new Date('2024-12-05T09:00:00'),
    completedAt: new Date('2024-12-05T09:00:15'),
  },
  {
    id: 'txn_005',
    accountId: 'acc_004',
    type: 'debit',
    amount: 12.50,
    currency: 'USD',
    status: 'completed',
    description: 'Crypto price monitoring',
    category: 'monitoring',
    metadata: {
      apiEndpoint: '/api/v1/crypto/prices',
      requestId: 'req_ghi012',
      agentAction: 'price_check',
    },
    createdAt: new Date('2024-12-05T08:45:00'),
    completedAt: new Date('2024-12-05T08:45:01'),
  },
  {
    id: 'txn_006',
    accountId: 'acc_002',
    type: 'credit',
    amount: 100.00,
    currency: 'USD',
    status: 'completed',
    description: 'Account top-up',
    category: 'deposit',
    createdAt: new Date('2024-12-03T16:30:00'),
    completedAt: new Date('2024-12-03T16:30:03'),
  },
];

// Sample Dashboard Stats
export const sampleDashboardStats: DashboardStats = {
  totalAccounts: 4,
  activeAccounts: 3,
  totalBalance: 7210.50,
  totalTransactions: 6,
  pendingTransactions: 0,
  paymentRequiredCount: 1,
  revenueThisMonth: 4810.50,
};
